# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  
  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXSYS";
      fsType = "ext4";
      options = [ "noatime" "commit=120" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/ZINIT";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ 
    {
      device = "/swapfile";
      size = 8192; 
      priority = 10;
    }
  ];
  
  zramSwap = {
    enable = true;
    algorithm = "zstd";
    memoryPercent = 50;
    priority = 100;
  };

  services.fstrim.enable = true;
  
}
